### PR TITLE
Fix wrong array instantiation syntax

### PR DESCRIPTION
**Pull request by christabella**
Otherwise it throws `TypeError: Cannot convert 10 to System.Int32[]`

Documented in https://github.com/pythonnet/pythonnet/issues/788 and https://github.com/pythonnet/pythonnet/issues/251

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/pythonnet/pythonnet.github.io?pullRequest=17) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/pythonnet/pythonnet.github.io?pullRequest=17) before we can accept your contribution.<br/><br/>:x: christabella [sign now](https://cla.dotnetfoundation.org/pythonnet/pythonnet.github.io?pullRequest=17)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/pythonnet/pythonnet.github.io?pullRequest=17) it.</sub>

**Comment by lostmsu** [comment]
I think the sample is correct, and Python.NET itself needs to be fixed if this is not working. This code is supposed to create an array of 10 `int`. E.g. it should be equivalent of `new int[10]`.

`myarray = Array[int](10)`

**Comment by lostmsu** [comment]
Published fix for Python.NET here: https://github.com/pythonnet/pythonnet/pull/1291

**Comment by christabella** [comment]
Thank you for pushing the fix

**Pull request closed without merging**
