### PR TITLE
updated documentation

### PR DESCRIPTION
**Pull request by denfromufa**

### CODE REVIEW

**Comment by denfromufa** [comment]
@filmor @vmuriart @tonyroberts please review documentation update. The motivation was outdated information on python guide: 

https://github.com/kennethreitz/python-guide/pull/746

**Comment by tonyroberts** [comment]
:+1:

**Comment by filmor** [comment]
Just one small thing: Do we really want people to use `npython`? Does that make sense at all, seeing that it's completely equivalent to running `python` and then importing `clr`?

**Comment by denfromufa** [comment]
@filmor npython is still useful for quickly troubleshooting the embedding cases:

https://github.com/pythonnet/pythonnet/search?q=npython&type=Issues

Also @cgohlke still bundles npython.exe in his wheels:

http://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet

**Comment by tonyroberts** [comment]
@denfromufa I agree with @filmor that it's better for new users to be pointed to the regular python instead of nPython, otherwise they might get the impression somehow using pythonnet *requires* npython. What about changing it to python, and adding a note that nPython is available as an example of embedding the CPython interpreter in a c# application?

**Comment by denfromufa** [comment]
Agreed! Let me change the purpose of nPython.exe in these docs from "using
pythonnet" to "example of embedding Python in .NET". The primary way to use
pythonnet should be "import clr" in python/ipython interpreter.

**Comment by denfromufa** [comment]
@tonyroberts @filmor done! please go through a second round of review.

**Comment by filmor** [comment]
Looks good to me.

**Comment by tonyroberts** [comment]
me too

**Comment by filmor** [comment]
Then squash and merge :)

**Comment by denfromufa** [comment]
I started working on draft release notes. Let's mark all issues to be
resolved for this release.

**Pull request merged**
