### PR TITLE
Use GH-Pages/Jekyll for rendering

### PR DESCRIPTION
**Pull request by vmuriart**
I did a fast conversion of the `.html` page to `.md`.

- Easier to diff and read the raw code.
- Syntax highlighting
- Cleaner formatting
- Removes repeated information between `index` and `readme`
- Easier to manage

The only "con" is that we lose the side-bar. It can be enabled though, just don't know how.

I set-up a preview page under my account. Any references to me will auto update when being rendered under the `pythonnet` acoount.

https://vmuriart.github.io/test_pages/

### CODE REVIEW

**Comment by denfromufa** [comment]
+1 will this render fine if pasted in our wiki? Just noticed C Python which should be CPython

**Comment by vmuriart** [comment]
@denfromufa it *should*. I have minimal experience with the wiki so I can't say for sure.

There's a couple typos/misformats still left in the document probably. I just did a quick convert/format without changing the actual content.

**Comment by denfromufa** [comment]
for comparison https://github.com/pythonnet/pythonnet/wiki/Extended-tutorial

**Comment by vmuriart** [comment]
Looks like it renders the same as it would on the branch repo homepage

https://github.com/pythonnet/pythonnet.github.io/tree/jekyll

**Comment by denfromufa** [comment]
@vmuriart i like the latter 2 links better than the first one.

**Comment by vmuriart** [comment]
@denfromufa which links are you referring to?

**Pull request merged**
