### PR TITLE
Remove Ironpython link

### PR DESCRIPTION
**Pull request by ShalokShalom**
Its not anymore in development since 2 years

### CODE REVIEW

**Comment by filmor** [comment]
We can drop the "active development" part, I still think the link should stay.

**Comment by ShalokShalom** [comment]
For what? Add "deprecated" to it?

**Comment by filmor** [comment]
It does still work, doesn't it? And it is exactly what is pointed out in the text, a purely-managed way to embed or execute Python.

**Comment by ShalokShalom** [comment]
Good to know, which kind of quality assurance is common here. Thanks

**Comment by denfromufa** [comment]
@ShalokShalom I agree with @filmor, IronPython still has its own domain of application, e.g. when all the code has to run on top of .NET runtime or when deep integration with .NET is necessary. There are few commercial applications which integrated IronPython for this reason.
IronPython definitely is not dead and is now part of .NET Foundation. Also Ironpython project developed DLR which is used in pythonnet, C# (dynamic) and even PowerShell.

**Comment by ShalokShalom** [comment]
Well, they changed the repo: https://github.com/IronLanguages/ironpython3

**Comment by ShalokShalom** [comment]
Their homepage is essentially outdated, thats all it.

**Pull request closed without merging**
